apiVersion: apps/v1
kind: Deployment
metadata:
  name: csap-testing
spec:
  selector:
    matchLabels:
      app: csap
  replicas: 3
  template:
    metadata:
      labels:
        app: csap
    spec:
      containers:
      - name: clopez-csap
        image: 192.168.1.109:5000/clopez/csap-arm:v1.0
        ports:
        - containerPort: 8080
      nodeSelector:
        system_model: raspberry-3
      hostAliases:
        - hostnames:
          - "raspi5"
          ip: "192.168.1.111"
